"""made razorpay's order_id, payment_id, signature to be null

Revision ID: 1affc8996f21
Revises: e089eceb1af8
Create Date: 2023-04-05 10:41:09.195473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1affc8996f21'
down_revision = 'e089eceb1af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('razorpay_order_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'yet to add'"))
        batch_op.alter_column('razorpay_payment_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'yet to add'"))
        batch_op.alter_column('razorpay_signature',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'yet to add'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('razorpay_signature',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'yet to add'"))
        batch_op.alter_column('razorpay_payment_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'yet to add'"))
        batch_op.alter_column('razorpay_order_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'yet to add'"))

    # ### end Alembic commands ###
